### ISSUE TITLE
No such method exception 

### ISSUE THREAD

**Issue by borag** [nats-io/nats-java-vertx-client#70]
### Observed behavior

I got an java.lang.NoSuchMethodError: 'void io.nats.client.impl.MessageQueue.<init>(boolean)'
When I upgraded "jnats" to 2.19.0 and tried to create JetStream definition.

### Expected behavior

It should work

### Server and client version

latest

### Steps to reproduce

Just upgrade "jnats" to 2.19.0 or any 2.17.4+

**Comment by borag** [comment]
It also does not persist messages to JetStream but does not give an error.

**Comment by azilly-de** [comment]
@borag

This is due the fact that jNATS 2.17.4 introduced a breaking API Change on MessageQueue with introduction
a REQUEST_CLEANUP_INTERVAL

e.g.
        super(true, Options.DEFAULT_REQUEST_CLEANUP_INTERVAL);
        
This API change can be hidden, but IMHO could potentially introduce behaviour change.

**Comment by scottf** [comment]
It's actually not a breaking change since JNats MessageQueue is not public. The next release will address this.
